language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - sudo apt-get -y update
  - sudo apt-get -y install python3-pip
  - sudo apt-get -y install python3-dev python3-setuptools
install:
  - pip install -r requirements.txt
script:
  - py.test
